# Dockerfile to be used as an init container
# this Docker file installs tiny-cni binary & config at the right place on host

# Stage build
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o bin/tiny-cni ./cmd/tiny-cni/

# Stage run
FROM alpine:latest AS runtime

WORKDIR /app

COPY --from=builder /app/bin/tiny-cni .
COPY --from=builder /app/docker/config-default.json .
COPY --from=builder /app/docker/deploy.sh .

ENTRYPOINT ["./deploy.sh"]
